export const NAVIGATION = {
  splash: 'Splash',
  home: 'Home',
  homeManga: 'Home Manga',
  comicDetails: 'ComicDetails',
  comicBook: 'ComicBook',
  mockBooks: 'MockBooks',
  downloadComicBook: 'DownloadComicBook',
  search: 'Search',
  bookmarks: 'Bookmarks',
  settings: 'Settings',
  communityBoard: 'Community',
  bottomNavigation: 'BottomNavigation',
  aboutUs: 'AboutUs',
  update: 'Update',
  animeVideo: 'AnimeVideo',
  animeDetails: 'AnimeDetails',
  mangaDetails: 'MangaDetails',
  mangaBook: 'MangaBook',
  mangaSearch: 'MangaSearch',
  mangaViewAll: 'MangaViewAll',
  ViewAll: 'ViewAll',
  offlineComic: 'Downloaded',
  seeAll: 'SeeAll',
  sources: 'Web Sources',
  WebSources: 'WebSources',
  WebSourcesList: 'WebSourcesList',
  WebSearch: 'WebSearch',
  Library: 'Library',
};
