export const NAVIGATION = {
  splash: 'Splash',
  home: 'Home',
  comicDetails: 'ComicDetails',
  comicBook: 'ComicBook',
  search: 'Search',
  bookmarks: 'History',
  settings: 'Settings',
  sources: 'Sources',
  bottomNavigation: 'BottomNavigation',
  aboutUs: 'AboutUs',
  update: 'Update',
  animeVideo: 'AnimeVideo',
  animeDetails: 'AnimeDetails',
  moreDetails: 'MoreDetails',
  ViewAll: "ViewAll",
  offlineComic: "Offline",
};
