require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'InkNest-macOS' do
  platform :macos, '11.0'

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => false,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Manually include only macOS-compatible modules
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'dr-pogodin-react-native-fs', :path => '../node_modules/@dr.pogodin/react-native-fs'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  post_install do |installer|
    react_native_post_install(installer)
  end
end